import = ["~/.config/alacritty/themes/dracula.toml"]

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 11.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 5
y = 5
